### ISSUE TITLE
Not able to open encrypted pdf

### ISSUE THREAD

**Issue by nitin2953** [hyzyla/pdfium#10]
I'm trying to load these file, but it is always showing same error

- [z-enc.pdf](https://github.com/user-attachments/files/16370218/z-enc.pdf)
  Encryption: AES 128-bit
  Password: 12345678
- Private File
  Encryption: RC4 128-bit

**Both are opening without any error in any pdf viewer**

```js
const buff = await fs.readFile('z-enc.pdf')
const library = await PDFiumLibrary.init();

const password = "12345678";
const document = await library.loadDocument(buff, password);
const page = document.getPage(0)
```

Error
```
C:\Users\user\Desktop\PDF\node_modules\@hyzyla\pdfium\dist\library.js:52
                throw new Error(`PDF Loading = ${lastError}`);
                      ^

Error: PDF Loading = 4
    at PDFiumLibrary.<anonymous> (C:\Users\user\Desktop\PDF\node_modules\@hyzyla\pdfium\dist\library.js:52:23)
    at Generator.next (<anonymous>)
    at C:\Users\user\Desktop\PDF\node_modules\@hyzyla\pdfium\dist\library.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\Desktop\PDF\node_modules\@hyzyla\pdfium\dist\library.js:4:12)
    at PDFiumLibrary.loadDocument (C:\Users\user\Desktop\PDF\node_modules\@hyzyla\pdfium\dist\library.js:37:16)
    at main (C:\Users\user\Desktop\PDF\pdfium.js:9:33)

Node.js v22.1.0
```

**Comment by hyzyla** [comment]
PDFium was expecting a C string, and I just assumed by mistake (why?) that Emscripten somehow magically converts a JavaScript string to a C string

**Comment by hyzyla** [comment]
This issue is fixed in three latest release
